###################################################################
###                           MODULES                           ###
###################################################################
# In this section you can toggle each module.                     #
# For the case you don't need one of the modules NetworkUtilities #
# offers, you can simply disable it. This will also save some     #
# performance because the module isn't even loaded.               #
###################################################################

# SERVER NOTIFICATIONS MODULE #
# This module allows to disable server join and quit messages.
# It is recommended to enable this module if you use the plugin's
# connectionNotifications system on the proxy.
# Note that this setting might be overwritten by some other plugins
# that are loaded after this one.
serverNotifications:
  disableJoinMessages: true   # disable the server join messages
  disableQuitMessages: true   # disable the server quit/leave messages



### DON'T EDIT ANYTHING BELOW THIS LINE ###
configVersion: "1.0.0"
